language: node_js

node_js:
 - "0.10"
 - "4"

addons:
    code_climate:
        repo_token: 3af78c71b999d36106cc3ec8761fa5d664515fef7b8c8698e9d5f091a9d5c5a3

branches:
  only:
    - develop
    - master

sudo: false

before_install:
 - npm install -g grunt-cli

install:
 - npm install
